ui:
  title: "Analytics Dashboard Pro"
  layout: "wide"
  theme: "light"
  
modules:
  sidebar: True
  data_upload: True
  visualization_types: ["bar", "line", "scatter"]
  
styles:
  primary_color: "#2c3e50"
  secondary_color: "#3498db"